server:
  port: ${app.port:8080}
spring:
  application:
    name: restaurant-apigw
  config:
    import: configserver:http://127.0.0.1:8888
  cloud:
    discovery:
      enabled: true
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: restaurant-routes
          predicates:
            - Path=/api/v1/restaurant/**
          uri: lb://RESTAURANT
